name: ci

on:
  push:
    branches:
      - main
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.GENERIC_PASSWORD }}
        repository: hayond/esmodule-server
        short-description: ${{ github.event.repository.description }}
