name: ci

on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            hayond/esmodule-server:latest
            hayond/esmodule-server:${{github.ref_name}}